# Generated by Django 2.2.24 on 2021-11-19 23:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211119_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fotoCapa',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=75, size=[400, 300], upload_to=''),
        ),
    ]
