# Generated by Django 2.2.24 on 2021-11-23 18:08

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211119_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fotoCapa',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='png', keep_meta=True, null=True, quality=75, size=[400, 300], upload_to='media/'),
        ),
    ]
