# Generated by Django 2.2.24 on 2021-11-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211123_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='campoURL',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
