# Generated by Django 2.2.24 on 2021-11-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_campourl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='campoURL',
            new_name='campoURL1',
        ),
        migrations.AddField(
            model_name='post',
            name='campoURL2',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='post',
            name='campoURL3',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
